package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.DeviceAlarmRecord;
import com.aw.braceletserver.entity.DeviceAlarmRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceAlarmRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	long countByExample(DeviceAlarmRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int deleteByExample(DeviceAlarmRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int insert(DeviceAlarmRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int insertSelective(DeviceAlarmRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	List<DeviceAlarmRecord> selectByExample(DeviceAlarmRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	DeviceAlarmRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") DeviceAlarmRecord record,
			@Param("example") DeviceAlarmRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int updateByExample(@Param("record") DeviceAlarmRecord record, @Param("example") DeviceAlarmRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int updateByPrimaryKeySelective(DeviceAlarmRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	int updateByPrimaryKey(DeviceAlarmRecord record);
}