package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.DevicePosition;
import com.aw.braceletserver.entity.DevicePositionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface DevicePositionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	long countByExample(DevicePositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int deleteByExample(DevicePositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int insert(DevicePosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int insertSelective(DevicePosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	List<DevicePosition> selectByExample(DevicePositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	DevicePosition selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int updateByExampleSelective(@Param("record") DevicePosition record,
			@Param("example") DevicePositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int updateByExample(@Param("record") DevicePosition record, @Param("example") DevicePositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int updateByPrimaryKeySelective(DevicePosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_position
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	int updateByPrimaryKey(DevicePosition record);

	Integer selectMaxDevicePositionId();
}