package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.DeviceEventRemind;
import com.aw.braceletserver.entity.DeviceEventRemindExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceEventRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    int countByExample(DeviceEventRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    int deleteByExample(DeviceEventRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    int insert(DeviceEventRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    int insertSelective(DeviceEventRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    List<DeviceEventRemind> selectByExample(DeviceEventRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeviceEventRemind record, @Param("example") DeviceEventRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    int updateByExample(@Param("record") DeviceEventRemind record, @Param("example") DeviceEventRemindExample example);
}