package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.Device;
import com.aw.braceletserver.entity.DeviceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int deleteByPrimaryKey(String serialNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    Device selectByPrimaryKey(String serialNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    int updateByPrimaryKey(Device record);

    List<Device> selectDeviceByUserId(int userId);
    
    Integer selectMaxDeviceId();
}