package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.DeviceGeofence;
import com.aw.braceletserver.entity.DeviceGeofenceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceGeofenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int countByExample(DeviceGeofenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int deleteByExample(DeviceGeofenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int insert(DeviceGeofence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int insertSelective(DeviceGeofence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    List<DeviceGeofence> selectByExample(DeviceGeofenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    DeviceGeofence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeviceGeofence record, @Param("example") DeviceGeofenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int updateByExample(@Param("record") DeviceGeofence record, @Param("example") DeviceGeofenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceGeofence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_geofence
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    int updateByPrimaryKey(DeviceGeofence record);

    int getNextGeofenceId();
}