package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.DeviceCommand;
import com.aw.braceletserver.entity.DeviceCommandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceCommandMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	long countByExample(DeviceCommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int deleteByExample(DeviceCommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int insert(DeviceCommand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int insertSelective(DeviceCommand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	List<DeviceCommand> selectByExample(DeviceCommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	DeviceCommand selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int updateByExampleSelective(@Param("record") DeviceCommand record, @Param("example") DeviceCommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int updateByExample(@Param("record") DeviceCommand record, @Param("example") DeviceCommandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int updateByPrimaryKeySelective(DeviceCommand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	int updateByPrimaryKey(DeviceCommand record);

	int selectNextId();
}