package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.Dic;
import com.aw.braceletserver.entity.DicExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    long countByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int deleteByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int deleteByPrimaryKey(String dicCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int insert(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int insertSelective(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    List<Dic> selectByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    Dic selectByPrimaryKey(String dicCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Dic record, @Param("example") DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int updateByExample(@Param("record") Dic record, @Param("example") DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int updateByPrimaryKeySelective(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    int updateByPrimaryKey(Dic record);
}