package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.Health;
import com.aw.braceletserver.entity.HealthExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HealthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int countByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int deleteByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int insert(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int insertSelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    List<Health> selectByExample(HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    Health selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int updateByExample(@Param("record") Health record, @Param("example") HealthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int updateByPrimaryKeySelective(Health record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    int updateByPrimaryKey(Health record);
}