package com.aw.braceletserver.mapper;

import com.aw.braceletserver.entity.TxUser;
import com.aw.braceletserver.entity.TxUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int countByExample(TxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int deleteByExample(TxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int insert(TxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int insertSelective(TxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    List<TxUser> selectByExample(TxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    TxUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TxUser record, @Param("example") TxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int updateByExample(@Param("record") TxUser record, @Param("example") TxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int updateByPrimaryKeySelective(TxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_user
     *
     * @mbggenerated Sat May 18 23:17:54 CST 2019
     */
    int updateByPrimaryKey(TxUser record);

    TxUser selectLogin(Map<String, Object> map);
	
    Integer selectMaxId();

    List<Map<String, Object>> selectAllDeviceData();
}