server:
  port: 8080
spring:
  application:
    name: BraceletServer
  cache:
    type: ehcache
    ehcache:
      config: classpath:/myehcache.xml
  mvc:
    #配置静态资源
    static-path-pattern: /static/**
  #数据源配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/tianwen?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Mysql_200
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

##该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.aw.braceletserver.model  #注意：对应实体类的路径
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true

##pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      aw:
        braceletserver: debug

oviphone:
  presetuser:
    name: aowei
    pass: 123456
  api-uri:
    #域名
    domain: http://121.41.62.200
    #登陆接口
    login: http://www.aiday.com.cn:10502/api/User/Login
    #设备最新位置和设备基本信息接口
    equiment-info: ${oviphone.api-uri.domain}/api/Device/PersonDeviceList
    #健康数据接口
    health-info: ${oviphone.api-uri.domain}/api/Health/GetHealth
    #指令下发接口——关机和设置阈值时使用
    send-cmd: ${oviphone.api-uri.domain}/api/Command/SendCommand
    #历史轨迹接口
    history-track: ${oviphone.api-uri.domain}/api/Location/History
    #历史报警信息接口
    history-warnmsg: ${oviphone.api-uri.domain}/api/ExceptionMessage/ExcdeptionListWhitoutCode

