package com.aw.braceletserver.entity;

import java.util.Date;

public class DeviceCommand {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.ID
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.SERIAL_NUMBER
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private String serialNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.DEVICE_ID
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.DEVICE_MODEL
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private Integer deviceModel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.CMD_CODE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private String cmdCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.CMD_NAME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private String cmdName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.CMD_VALUE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private String cmdValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.SMS_TYPE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private String smsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.SMS_CONTENT
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private String smsContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.CREATE_TIME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_command.UPDATE_TIME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.ID
	 * @return  the value of device_command.ID
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.ID
	 * @param id  the value for device_command.ID
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.SERIAL_NUMBER
	 * @return  the value of device_command.SERIAL_NUMBER
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.SERIAL_NUMBER
	 * @param serialNumber  the value for device_command.SERIAL_NUMBER
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.DEVICE_ID
	 * @return  the value of device_command.DEVICE_ID
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.DEVICE_ID
	 * @param deviceId  the value for device_command.DEVICE_ID
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.DEVICE_MODEL
	 * @return  the value of device_command.DEVICE_MODEL
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Integer getDeviceModel() {
		return deviceModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.DEVICE_MODEL
	 * @param deviceModel  the value for device_command.DEVICE_MODEL
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setDeviceModel(Integer deviceModel) {
		this.deviceModel = deviceModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.CMD_CODE
	 * @return  the value of device_command.CMD_CODE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getCmdCode() {
		return cmdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.CMD_CODE
	 * @param cmdCode  the value for device_command.CMD_CODE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setCmdCode(String cmdCode) {
		this.cmdCode = cmdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.CMD_NAME
	 * @return  the value of device_command.CMD_NAME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getCmdName() {
		return cmdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.CMD_NAME
	 * @param cmdName  the value for device_command.CMD_NAME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.CMD_VALUE
	 * @return  the value of device_command.CMD_VALUE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getCmdValue() {
		return cmdValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.CMD_VALUE
	 * @param cmdValue  the value for device_command.CMD_VALUE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setCmdValue(String cmdValue) {
		this.cmdValue = cmdValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.SMS_TYPE
	 * @return  the value of device_command.SMS_TYPE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getSmsType() {
		return smsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.SMS_TYPE
	 * @param smsType  the value for device_command.SMS_TYPE
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setSmsType(String smsType) {
		this.smsType = smsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.SMS_CONTENT
	 * @return  the value of device_command.SMS_CONTENT
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getSmsContent() {
		return smsContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.SMS_CONTENT
	 * @param smsContent  the value for device_command.SMS_CONTENT
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setSmsContent(String smsContent) {
		this.smsContent = smsContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.CREATE_TIME
	 * @return  the value of device_command.CREATE_TIME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.CREATE_TIME
	 * @param createTime  the value for device_command.CREATE_TIME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_command.UPDATE_TIME
	 * @return  the value of device_command.UPDATE_TIME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_command.UPDATE_TIME
	 * @param updateTime  the value for device_command.UPDATE_TIME
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}