package com.aw.braceletserver.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceCommandExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public DeviceCommandExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSerialNumberIsNull() {
			addCriterion("SERIAL_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andSerialNumberIsNotNull() {
			addCriterion("SERIAL_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andSerialNumberEqualTo(String value) {
			addCriterion("SERIAL_NUMBER =", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotEqualTo(String value) {
			addCriterion("SERIAL_NUMBER <>", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberGreaterThan(String value) {
			addCriterion("SERIAL_NUMBER >", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberGreaterThanOrEqualTo(String value) {
			addCriterion("SERIAL_NUMBER >=", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberLessThan(String value) {
			addCriterion("SERIAL_NUMBER <", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberLessThanOrEqualTo(String value) {
			addCriterion("SERIAL_NUMBER <=", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberLike(String value) {
			addCriterion("SERIAL_NUMBER like", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotLike(String value) {
			addCriterion("SERIAL_NUMBER not like", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberIn(List<String> values) {
			addCriterion("SERIAL_NUMBER in", values, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotIn(List<String> values) {
			addCriterion("SERIAL_NUMBER not in", values, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberBetween(String value1, String value2) {
			addCriterion("SERIAL_NUMBER between", value1, value2, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotBetween(String value1, String value2) {
			addCriterion("SERIAL_NUMBER not between", value1, value2, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNull() {
			addCriterion("DEVICE_ID is null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNotNull() {
			addCriterion("DEVICE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdEqualTo(Integer value) {
			addCriterion("DEVICE_ID =", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotEqualTo(Integer value) {
			addCriterion("DEVICE_ID <>", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThan(Integer value) {
			addCriterion("DEVICE_ID >", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEVICE_ID >=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThan(Integer value) {
			addCriterion("DEVICE_ID <", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
			addCriterion("DEVICE_ID <=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIn(List<Integer> values) {
			addCriterion("DEVICE_ID in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotIn(List<Integer> values) {
			addCriterion("DEVICE_ID not in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
			addCriterion("DEVICE_ID between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("DEVICE_ID not between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceModelIsNull() {
			addCriterion("DEVICE_MODEL is null");
			return (Criteria) this;
		}

		public Criteria andDeviceModelIsNotNull() {
			addCriterion("DEVICE_MODEL is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceModelEqualTo(Integer value) {
			addCriterion("DEVICE_MODEL =", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotEqualTo(Integer value) {
			addCriterion("DEVICE_MODEL <>", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelGreaterThan(Integer value) {
			addCriterion("DEVICE_MODEL >", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelGreaterThanOrEqualTo(Integer value) {
			addCriterion("DEVICE_MODEL >=", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelLessThan(Integer value) {
			addCriterion("DEVICE_MODEL <", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelLessThanOrEqualTo(Integer value) {
			addCriterion("DEVICE_MODEL <=", value, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelIn(List<Integer> values) {
			addCriterion("DEVICE_MODEL in", values, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotIn(List<Integer> values) {
			addCriterion("DEVICE_MODEL not in", values, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelBetween(Integer value1, Integer value2) {
			addCriterion("DEVICE_MODEL between", value1, value2, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andDeviceModelNotBetween(Integer value1, Integer value2) {
			addCriterion("DEVICE_MODEL not between", value1, value2, "deviceModel");
			return (Criteria) this;
		}

		public Criteria andCmdCodeIsNull() {
			addCriterion("CMD_CODE is null");
			return (Criteria) this;
		}

		public Criteria andCmdCodeIsNotNull() {
			addCriterion("CMD_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCmdCodeEqualTo(String value) {
			addCriterion("CMD_CODE =", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeNotEqualTo(String value) {
			addCriterion("CMD_CODE <>", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeGreaterThan(String value) {
			addCriterion("CMD_CODE >", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CMD_CODE >=", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeLessThan(String value) {
			addCriterion("CMD_CODE <", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeLessThanOrEqualTo(String value) {
			addCriterion("CMD_CODE <=", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeLike(String value) {
			addCriterion("CMD_CODE like", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeNotLike(String value) {
			addCriterion("CMD_CODE not like", value, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeIn(List<String> values) {
			addCriterion("CMD_CODE in", values, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeNotIn(List<String> values) {
			addCriterion("CMD_CODE not in", values, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeBetween(String value1, String value2) {
			addCriterion("CMD_CODE between", value1, value2, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdCodeNotBetween(String value1, String value2) {
			addCriterion("CMD_CODE not between", value1, value2, "cmdCode");
			return (Criteria) this;
		}

		public Criteria andCmdNameIsNull() {
			addCriterion("CMD_NAME is null");
			return (Criteria) this;
		}

		public Criteria andCmdNameIsNotNull() {
			addCriterion("CMD_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andCmdNameEqualTo(String value) {
			addCriterion("CMD_NAME =", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameNotEqualTo(String value) {
			addCriterion("CMD_NAME <>", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameGreaterThan(String value) {
			addCriterion("CMD_NAME >", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameGreaterThanOrEqualTo(String value) {
			addCriterion("CMD_NAME >=", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameLessThan(String value) {
			addCriterion("CMD_NAME <", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameLessThanOrEqualTo(String value) {
			addCriterion("CMD_NAME <=", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameLike(String value) {
			addCriterion("CMD_NAME like", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameNotLike(String value) {
			addCriterion("CMD_NAME not like", value, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameIn(List<String> values) {
			addCriterion("CMD_NAME in", values, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameNotIn(List<String> values) {
			addCriterion("CMD_NAME not in", values, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameBetween(String value1, String value2) {
			addCriterion("CMD_NAME between", value1, value2, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdNameNotBetween(String value1, String value2) {
			addCriterion("CMD_NAME not between", value1, value2, "cmdName");
			return (Criteria) this;
		}

		public Criteria andCmdValueIsNull() {
			addCriterion("CMD_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andCmdValueIsNotNull() {
			addCriterion("CMD_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andCmdValueEqualTo(String value) {
			addCriterion("CMD_VALUE =", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueNotEqualTo(String value) {
			addCriterion("CMD_VALUE <>", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueGreaterThan(String value) {
			addCriterion("CMD_VALUE >", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueGreaterThanOrEqualTo(String value) {
			addCriterion("CMD_VALUE >=", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueLessThan(String value) {
			addCriterion("CMD_VALUE <", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueLessThanOrEqualTo(String value) {
			addCriterion("CMD_VALUE <=", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueLike(String value) {
			addCriterion("CMD_VALUE like", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueNotLike(String value) {
			addCriterion("CMD_VALUE not like", value, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueIn(List<String> values) {
			addCriterion("CMD_VALUE in", values, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueNotIn(List<String> values) {
			addCriterion("CMD_VALUE not in", values, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueBetween(String value1, String value2) {
			addCriterion("CMD_VALUE between", value1, value2, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andCmdValueNotBetween(String value1, String value2) {
			addCriterion("CMD_VALUE not between", value1, value2, "cmdValue");
			return (Criteria) this;
		}

		public Criteria andSmsTypeIsNull() {
			addCriterion("SMS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andSmsTypeIsNotNull() {
			addCriterion("SMS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSmsTypeEqualTo(String value) {
			addCriterion("SMS_TYPE =", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeNotEqualTo(String value) {
			addCriterion("SMS_TYPE <>", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeGreaterThan(String value) {
			addCriterion("SMS_TYPE >", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeGreaterThanOrEqualTo(String value) {
			addCriterion("SMS_TYPE >=", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeLessThan(String value) {
			addCriterion("SMS_TYPE <", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeLessThanOrEqualTo(String value) {
			addCriterion("SMS_TYPE <=", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeLike(String value) {
			addCriterion("SMS_TYPE like", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeNotLike(String value) {
			addCriterion("SMS_TYPE not like", value, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeIn(List<String> values) {
			addCriterion("SMS_TYPE in", values, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeNotIn(List<String> values) {
			addCriterion("SMS_TYPE not in", values, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeBetween(String value1, String value2) {
			addCriterion("SMS_TYPE between", value1, value2, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsTypeNotBetween(String value1, String value2) {
			addCriterion("SMS_TYPE not between", value1, value2, "smsType");
			return (Criteria) this;
		}

		public Criteria andSmsContentIsNull() {
			addCriterion("SMS_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andSmsContentIsNotNull() {
			addCriterion("SMS_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andSmsContentEqualTo(String value) {
			addCriterion("SMS_CONTENT =", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentNotEqualTo(String value) {
			addCriterion("SMS_CONTENT <>", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentGreaterThan(String value) {
			addCriterion("SMS_CONTENT >", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentGreaterThanOrEqualTo(String value) {
			addCriterion("SMS_CONTENT >=", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentLessThan(String value) {
			addCriterion("SMS_CONTENT <", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentLessThanOrEqualTo(String value) {
			addCriterion("SMS_CONTENT <=", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentLike(String value) {
			addCriterion("SMS_CONTENT like", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentNotLike(String value) {
			addCriterion("SMS_CONTENT not like", value, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentIn(List<String> values) {
			addCriterion("SMS_CONTENT in", values, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentNotIn(List<String> values) {
			addCriterion("SMS_CONTENT not in", values, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentBetween(String value1, String value2) {
			addCriterion("SMS_CONTENT between", value1, value2, "smsContent");
			return (Criteria) this;
		}

		public Criteria andSmsContentNotBetween(String value1, String value2) {
			addCriterion("SMS_CONTENT not between", value1, value2, "smsContent");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_command
	 * @mbg.generated  Sat Nov 16 14:25:09 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_command
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 10:29:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}