package com.aw.braceletserver.entity;

import java.util.Date;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.SERIAL_NUMBER
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.DEVICE_ID
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.DEVICE_NAME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.NICK_NAME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.DEVICE_TYPE
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private Integer deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.STATUS
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.CREATE_TIME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.REMARK
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.SERIAL_NUMBER
     *
     * @return the value of device.SERIAL_NUMBER
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.SERIAL_NUMBER
     *
     * @param serialNumber the value for device.SERIAL_NUMBER
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.DEVICE_ID
     *
     * @return the value of device.DEVICE_ID
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.DEVICE_ID
     *
     * @param deviceId the value for device.DEVICE_ID
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.DEVICE_NAME
     *
     * @return the value of device.DEVICE_NAME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.DEVICE_NAME
     *
     * @param deviceName the value for device.DEVICE_NAME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.NICK_NAME
     *
     * @return the value of device.NICK_NAME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.NICK_NAME
     *
     * @param nickName the value for device.NICK_NAME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.DEVICE_TYPE
     *
     * @return the value of device.DEVICE_TYPE
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.DEVICE_TYPE
     *
     * @param deviceType the value for device.DEVICE_TYPE
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.STATUS
     *
     * @return the value of device.STATUS
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.STATUS
     *
     * @param status the value for device.STATUS
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.CREATE_TIME
     *
     * @return the value of device.CREATE_TIME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.CREATE_TIME
     *
     * @param createTime the value for device.CREATE_TIME
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.REMARK
     *
     * @return the value of device.REMARK
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.REMARK
     *
     * @param remark the value for device.REMARK
     *
     * @mbggenerated Sun May 19 22:54:34 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}