package com.aw.braceletserver.entity;

import java.util.Date;

public class DeviceGeofence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.ID
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.NAME
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.LATITUDE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.LONGITUDE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.RADIUS
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Integer radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.FENCE_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Integer fenceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.ALARM_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Integer alarmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.ADDRESS
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.DEVICE_ID
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.GPS_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private String gpsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_geofence.CREATE_TIME
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.ID
     *
     * @return the value of device_geofence.ID
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.ID
     *
     * @param id the value for device_geofence.ID
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.NAME
     *
     * @return the value of device_geofence.NAME
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.NAME
     *
     * @param name the value for device_geofence.NAME
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.LATITUDE
     *
     * @return the value of device_geofence.LATITUDE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.LATITUDE
     *
     * @param latitude the value for device_geofence.LATITUDE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.LONGITUDE
     *
     * @return the value of device_geofence.LONGITUDE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.LONGITUDE
     *
     * @param longitude the value for device_geofence.LONGITUDE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.RADIUS
     *
     * @return the value of device_geofence.RADIUS
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Integer getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.RADIUS
     *
     * @param radius the value for device_geofence.RADIUS
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setRadius(Integer radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.FENCE_TYPE
     *
     * @return the value of device_geofence.FENCE_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Integer getFenceType() {
        return fenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.FENCE_TYPE
     *
     * @param fenceType the value for device_geofence.FENCE_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setFenceType(Integer fenceType) {
        this.fenceType = fenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.ALARM_TYPE
     *
     * @return the value of device_geofence.ALARM_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Integer getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.ALARM_TYPE
     *
     * @param alarmType the value for device_geofence.ALARM_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setAlarmType(Integer alarmType) {
        this.alarmType = alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.ADDRESS
     *
     * @return the value of device_geofence.ADDRESS
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.ADDRESS
     *
     * @param address the value for device_geofence.ADDRESS
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.DEVICE_ID
     *
     * @return the value of device_geofence.DEVICE_ID
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.DEVICE_ID
     *
     * @param deviceId the value for device_geofence.DEVICE_ID
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.GPS_TYPE
     *
     * @return the value of device_geofence.GPS_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public String getGpsType() {
        return gpsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.GPS_TYPE
     *
     * @param gpsType the value for device_geofence.GPS_TYPE
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setGpsType(String gpsType) {
        this.gpsType = gpsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_geofence.CREATE_TIME
     *
     * @return the value of device_geofence.CREATE_TIME
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_geofence.CREATE_TIME
     *
     * @param createTime the value for device_geofence.CREATE_TIME
     *
     * @mbggenerated Fri Jun 14 14:50:05 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}