package com.aw.braceletserver.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceAlarmRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public DeviceAlarmRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNull() {
			addCriterion("device_id is null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIsNotNull() {
			addCriterion("device_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceIdEqualTo(Integer value) {
			addCriterion("device_id =", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotEqualTo(Integer value) {
			addCriterion("device_id <>", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThan(Integer value) {
			addCriterion("device_id >", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("device_id >=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThan(Integer value) {
			addCriterion("device_id <", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
			addCriterion("device_id <=", value, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdIn(List<Integer> values) {
			addCriterion("device_id in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotIn(List<Integer> values) {
			addCriterion("device_id not in", values, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
			addCriterion("device_id between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("device_id not between", value1, value2, "deviceId");
			return (Criteria) this;
		}

		public Criteria andSerialNumberIsNull() {
			addCriterion("serial_number is null");
			return (Criteria) this;
		}

		public Criteria andSerialNumberIsNotNull() {
			addCriterion("serial_number is not null");
			return (Criteria) this;
		}

		public Criteria andSerialNumberEqualTo(String value) {
			addCriterion("serial_number =", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotEqualTo(String value) {
			addCriterion("serial_number <>", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberGreaterThan(String value) {
			addCriterion("serial_number >", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberGreaterThanOrEqualTo(String value) {
			addCriterion("serial_number >=", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberLessThan(String value) {
			addCriterion("serial_number <", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberLessThanOrEqualTo(String value) {
			addCriterion("serial_number <=", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberLike(String value) {
			addCriterion("serial_number like", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotLike(String value) {
			addCriterion("serial_number not like", value, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberIn(List<String> values) {
			addCriterion("serial_number in", values, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotIn(List<String> values) {
			addCriterion("serial_number not in", values, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberBetween(String value1, String value2) {
			addCriterion("serial_number between", value1, value2, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andSerialNumberNotBetween(String value1, String value2) {
			addCriterion("serial_number not between", value1, value2, "serialNumber");
			return (Criteria) this;
		}

		public Criteria andAlarmNameIsNull() {
			addCriterion("alarm_name is null");
			return (Criteria) this;
		}

		public Criteria andAlarmNameIsNotNull() {
			addCriterion("alarm_name is not null");
			return (Criteria) this;
		}

		public Criteria andAlarmNameEqualTo(String value) {
			addCriterion("alarm_name =", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameNotEqualTo(String value) {
			addCriterion("alarm_name <>", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameGreaterThan(String value) {
			addCriterion("alarm_name >", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameGreaterThanOrEqualTo(String value) {
			addCriterion("alarm_name >=", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameLessThan(String value) {
			addCriterion("alarm_name <", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameLessThanOrEqualTo(String value) {
			addCriterion("alarm_name <=", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameLike(String value) {
			addCriterion("alarm_name like", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameNotLike(String value) {
			addCriterion("alarm_name not like", value, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameIn(List<String> values) {
			addCriterion("alarm_name in", values, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameNotIn(List<String> values) {
			addCriterion("alarm_name not in", values, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameBetween(String value1, String value2) {
			addCriterion("alarm_name between", value1, value2, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmNameNotBetween(String value1, String value2) {
			addCriterion("alarm_name not between", value1, value2, "alarmName");
			return (Criteria) this;
		}

		public Criteria andAlarmContentIsNull() {
			addCriterion("alarm_content is null");
			return (Criteria) this;
		}

		public Criteria andAlarmContentIsNotNull() {
			addCriterion("alarm_content is not null");
			return (Criteria) this;
		}

		public Criteria andAlarmContentEqualTo(String value) {
			addCriterion("alarm_content =", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentNotEqualTo(String value) {
			addCriterion("alarm_content <>", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentGreaterThan(String value) {
			addCriterion("alarm_content >", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentGreaterThanOrEqualTo(String value) {
			addCriterion("alarm_content >=", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentLessThan(String value) {
			addCriterion("alarm_content <", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentLessThanOrEqualTo(String value) {
			addCriterion("alarm_content <=", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentLike(String value) {
			addCriterion("alarm_content like", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentNotLike(String value) {
			addCriterion("alarm_content not like", value, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentIn(List<String> values) {
			addCriterion("alarm_content in", values, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentNotIn(List<String> values) {
			addCriterion("alarm_content not in", values, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentBetween(String value1, String value2) {
			addCriterion("alarm_content between", value1, value2, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmContentNotBetween(String value1, String value2) {
			addCriterion("alarm_content not between", value1, value2, "alarmContent");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeIsNull() {
			addCriterion("alarm_type is null");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeIsNotNull() {
			addCriterion("alarm_type is not null");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeEqualTo(Integer value) {
			addCriterion("alarm_type =", value, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeNotEqualTo(Integer value) {
			addCriterion("alarm_type <>", value, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeGreaterThan(Integer value) {
			addCriterion("alarm_type >", value, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("alarm_type >=", value, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeLessThan(Integer value) {
			addCriterion("alarm_type <", value, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeLessThanOrEqualTo(Integer value) {
			addCriterion("alarm_type <=", value, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeIn(List<Integer> values) {
			addCriterion("alarm_type in", values, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeNotIn(List<Integer> values) {
			addCriterion("alarm_type not in", values, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeBetween(Integer value1, Integer value2) {
			addCriterion("alarm_type between", value1, value2, "alarmType");
			return (Criteria) this;
		}

		public Criteria andAlarmTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("alarm_type not between", value1, value2, "alarmType");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andIsDeleteIsNull() {
			addCriterion("is_delete is null");
			return (Criteria) this;
		}

		public Criteria andIsDeleteIsNotNull() {
			addCriterion("is_delete is not null");
			return (Criteria) this;
		}

		public Criteria andIsDeleteEqualTo(Integer value) {
			addCriterion("is_delete =", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteNotEqualTo(Integer value) {
			addCriterion("is_delete <>", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteGreaterThan(Integer value) {
			addCriterion("is_delete >", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_delete >=", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteLessThan(Integer value) {
			addCriterion("is_delete <", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
			addCriterion("is_delete <=", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteIn(List<Integer> values) {
			addCriterion("is_delete in", values, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteNotIn(List<Integer> values) {
			addCriterion("is_delete not in", values, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
			addCriterion("is_delete between", value1, value2, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
			addCriterion("is_delete not between", value1, value2, "isDelete");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return (Criteria) this;
		}

		public Criteria andLatitudeEqualTo(BigDecimal value) {
			addCriterion("latitude =", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotEqualTo(BigDecimal value) {
			addCriterion("latitude <>", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThan(BigDecimal value) {
			addCriterion("latitude >", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("latitude >=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThan(BigDecimal value) {
			addCriterion("latitude <", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("latitude <=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIn(List<BigDecimal> values) {
			addCriterion("latitude in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotIn(List<BigDecimal> values) {
			addCriterion("latitude not in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return (Criteria) this;
		}

		public Criteria andLongitudeEqualTo(BigDecimal value) {
			addCriterion("longitude =", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotEqualTo(BigDecimal value) {
			addCriterion("longitude <>", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThan(BigDecimal value) {
			addCriterion("longitude >", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("longitude >=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThan(BigDecimal value) {
			addCriterion("longitude <", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("longitude <=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIn(List<BigDecimal> values) {
			addCriterion("longitude in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotIn(List<BigDecimal> values) {
			addCriterion("longitude not in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIsNull() {
			addCriterion("device_name is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIsNotNull() {
			addCriterion("device_name is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNameEqualTo(String value) {
			addCriterion("device_name =", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotEqualTo(String value) {
			addCriterion("device_name <>", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameGreaterThan(String value) {
			addCriterion("device_name >", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
			addCriterion("device_name >=", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLessThan(String value) {
			addCriterion("device_name <", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLessThanOrEqualTo(String value) {
			addCriterion("device_name <=", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLike(String value) {
			addCriterion("device_name like", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotLike(String value) {
			addCriterion("device_name not like", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIn(List<String> values) {
			addCriterion("device_name in", values, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotIn(List<String> values) {
			addCriterion("device_name not in", values, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameBetween(String value1, String value2) {
			addCriterion("device_name between", value1, value2, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotBetween(String value1, String value2) {
			addCriterion("device_name not between", value1, value2, "deviceName");
			return (Criteria) this;
		}

		public Criteria andModelNameIsNull() {
			addCriterion("model_name is null");
			return (Criteria) this;
		}

		public Criteria andModelNameIsNotNull() {
			addCriterion("model_name is not null");
			return (Criteria) this;
		}

		public Criteria andModelNameEqualTo(String value) {
			addCriterion("model_name =", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameNotEqualTo(String value) {
			addCriterion("model_name <>", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameGreaterThan(String value) {
			addCriterion("model_name >", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameGreaterThanOrEqualTo(String value) {
			addCriterion("model_name >=", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameLessThan(String value) {
			addCriterion("model_name <", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameLessThanOrEqualTo(String value) {
			addCriterion("model_name <=", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameLike(String value) {
			addCriterion("model_name like", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameNotLike(String value) {
			addCriterion("model_name not like", value, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameIn(List<String> values) {
			addCriterion("model_name in", values, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameNotIn(List<String> values) {
			addCriterion("model_name not in", values, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameBetween(String value1, String value2) {
			addCriterion("model_name between", value1, value2, "modelName");
			return (Criteria) this;
		}

		public Criteria andModelNameNotBetween(String value1, String value2) {
			addCriterion("model_name not between", value1, value2, "modelName");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNull() {
			addCriterion("nickname is null");
			return (Criteria) this;
		}

		public Criteria andNicknameIsNotNull() {
			addCriterion("nickname is not null");
			return (Criteria) this;
		}

		public Criteria andNicknameEqualTo(String value) {
			addCriterion("nickname =", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotEqualTo(String value) {
			addCriterion("nickname <>", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThan(String value) {
			addCriterion("nickname >", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("nickname >=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThan(String value) {
			addCriterion("nickname <", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLessThanOrEqualTo(String value) {
			addCriterion("nickname <=", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameLike(String value) {
			addCriterion("nickname like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotLike(String value) {
			addCriterion("nickname not like", value, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameIn(List<String> values) {
			addCriterion("nickname in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotIn(List<String> values) {
			addCriterion("nickname not in", values, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameBetween(String value1, String value2) {
			addCriterion("nickname between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andNicknameNotBetween(String value1, String value2) {
			addCriterion("nickname not between", value1, value2, "nickname");
			return (Criteria) this;
		}

		public Criteria andAvatarIsNull() {
			addCriterion("avatar is null");
			return (Criteria) this;
		}

		public Criteria andAvatarIsNotNull() {
			addCriterion("avatar is not null");
			return (Criteria) this;
		}

		public Criteria andAvatarEqualTo(String value) {
			addCriterion("avatar =", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotEqualTo(String value) {
			addCriterion("avatar <>", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarGreaterThan(String value) {
			addCriterion("avatar >", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarGreaterThanOrEqualTo(String value) {
			addCriterion("avatar >=", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLessThan(String value) {
			addCriterion("avatar <", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLessThanOrEqualTo(String value) {
			addCriterion("avatar <=", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarLike(String value) {
			addCriterion("avatar like", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotLike(String value) {
			addCriterion("avatar not like", value, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarIn(List<String> values) {
			addCriterion("avatar in", values, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotIn(List<String> values) {
			addCriterion("avatar not in", values, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarBetween(String value1, String value2) {
			addCriterion("avatar between", value1, value2, "avatar");
			return (Criteria) this;
		}

		public Criteria andAvatarNotBetween(String value1, String value2) {
			addCriterion("avatar not between", value1, value2, "avatar");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdIsNull() {
			addCriterion("geo_fence_id is null");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdIsNotNull() {
			addCriterion("geo_fence_id is not null");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdEqualTo(Integer value) {
			addCriterion("geo_fence_id =", value, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdNotEqualTo(Integer value) {
			addCriterion("geo_fence_id <>", value, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdGreaterThan(Integer value) {
			addCriterion("geo_fence_id >", value, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("geo_fence_id >=", value, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdLessThan(Integer value) {
			addCriterion("geo_fence_id <", value, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdLessThanOrEqualTo(Integer value) {
			addCriterion("geo_fence_id <=", value, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdIn(List<Integer> values) {
			addCriterion("geo_fence_id in", values, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdNotIn(List<Integer> values) {
			addCriterion("geo_fence_id not in", values, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdBetween(Integer value1, Integer value2) {
			addCriterion("geo_fence_id between", value1, value2, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoFenceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("geo_fence_id not between", value1, value2, "geoFenceId");
			return (Criteria) this;
		}

		public Criteria andGeoNameIsNull() {
			addCriterion("geo_name is null");
			return (Criteria) this;
		}

		public Criteria andGeoNameIsNotNull() {
			addCriterion("geo_name is not null");
			return (Criteria) this;
		}

		public Criteria andGeoNameEqualTo(String value) {
			addCriterion("geo_name =", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameNotEqualTo(String value) {
			addCriterion("geo_name <>", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameGreaterThan(String value) {
			addCriterion("geo_name >", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameGreaterThanOrEqualTo(String value) {
			addCriterion("geo_name >=", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameLessThan(String value) {
			addCriterion("geo_name <", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameLessThanOrEqualTo(String value) {
			addCriterion("geo_name <=", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameLike(String value) {
			addCriterion("geo_name like", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameNotLike(String value) {
			addCriterion("geo_name not like", value, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameIn(List<String> values) {
			addCriterion("geo_name in", values, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameNotIn(List<String> values) {
			addCriterion("geo_name not in", values, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameBetween(String value1, String value2) {
			addCriterion("geo_name between", value1, value2, "geoName");
			return (Criteria) this;
		}

		public Criteria andGeoNameNotBetween(String value1, String value2) {
			addCriterion("geo_name not between", value1, value2, "geoName");
			return (Criteria) this;
		}

		public Criteria andFenceNoIsNull() {
			addCriterion("fence_no is null");
			return (Criteria) this;
		}

		public Criteria andFenceNoIsNotNull() {
			addCriterion("fence_no is not null");
			return (Criteria) this;
		}

		public Criteria andFenceNoEqualTo(Integer value) {
			addCriterion("fence_no =", value, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoNotEqualTo(Integer value) {
			addCriterion("fence_no <>", value, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoGreaterThan(Integer value) {
			addCriterion("fence_no >", value, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("fence_no >=", value, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoLessThan(Integer value) {
			addCriterion("fence_no <", value, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoLessThanOrEqualTo(Integer value) {
			addCriterion("fence_no <=", value, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoIn(List<Integer> values) {
			addCriterion("fence_no in", values, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoNotIn(List<Integer> values) {
			addCriterion("fence_no not in", values, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoBetween(Integer value1, Integer value2) {
			addCriterion("fence_no between", value1, value2, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andFenceNoNotBetween(Integer value1, Integer value2) {
			addCriterion("fence_no not between", value1, value2, "fenceNo");
			return (Criteria) this;
		}

		public Criteria andOlatIsNull() {
			addCriterion("olat is null");
			return (Criteria) this;
		}

		public Criteria andOlatIsNotNull() {
			addCriterion("olat is not null");
			return (Criteria) this;
		}

		public Criteria andOlatEqualTo(BigDecimal value) {
			addCriterion("olat =", value, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatNotEqualTo(BigDecimal value) {
			addCriterion("olat <>", value, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatGreaterThan(BigDecimal value) {
			addCriterion("olat >", value, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("olat >=", value, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatLessThan(BigDecimal value) {
			addCriterion("olat <", value, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatLessThanOrEqualTo(BigDecimal value) {
			addCriterion("olat <=", value, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatIn(List<BigDecimal> values) {
			addCriterion("olat in", values, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatNotIn(List<BigDecimal> values) {
			addCriterion("olat not in", values, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("olat between", value1, value2, "olat");
			return (Criteria) this;
		}

		public Criteria andOlatNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("olat not between", value1, value2, "olat");
			return (Criteria) this;
		}

		public Criteria andOlngIsNull() {
			addCriterion("olng is null");
			return (Criteria) this;
		}

		public Criteria andOlngIsNotNull() {
			addCriterion("olng is not null");
			return (Criteria) this;
		}

		public Criteria andOlngEqualTo(BigDecimal value) {
			addCriterion("olng =", value, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngNotEqualTo(BigDecimal value) {
			addCriterion("olng <>", value, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngGreaterThan(BigDecimal value) {
			addCriterion("olng >", value, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("olng >=", value, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngLessThan(BigDecimal value) {
			addCriterion("olng <", value, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngLessThanOrEqualTo(BigDecimal value) {
			addCriterion("olng <=", value, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngIn(List<BigDecimal> values) {
			addCriterion("olng in", values, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngNotIn(List<BigDecimal> values) {
			addCriterion("olng not in", values, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("olng between", value1, value2, "olng");
			return (Criteria) this;
		}

		public Criteria andOlngNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("olng not between", value1, value2, "olng");
			return (Criteria) this;
		}

		public Criteria andAltitudeIsNull() {
			addCriterion("altitude is null");
			return (Criteria) this;
		}

		public Criteria andAltitudeIsNotNull() {
			addCriterion("altitude is not null");
			return (Criteria) this;
		}

		public Criteria andAltitudeEqualTo(Float value) {
			addCriterion("altitude =", value, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeNotEqualTo(Float value) {
			addCriterion("altitude <>", value, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeGreaterThan(Float value) {
			addCriterion("altitude >", value, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("altitude >=", value, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeLessThan(Float value) {
			addCriterion("altitude <", value, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeLessThanOrEqualTo(Float value) {
			addCriterion("altitude <=", value, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeIn(List<Float> values) {
			addCriterion("altitude in", values, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeNotIn(List<Float> values) {
			addCriterion("altitude not in", values, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeBetween(Float value1, Float value2) {
			addCriterion("altitude between", value1, value2, "altitude");
			return (Criteria) this;
		}

		public Criteria andAltitudeNotBetween(Float value1, Float value2) {
			addCriterion("altitude not between", value1, value2, "altitude");
			return (Criteria) this;
		}

		public Criteria andBatteryIsNull() {
			addCriterion("battery is null");
			return (Criteria) this;
		}

		public Criteria andBatteryIsNotNull() {
			addCriterion("battery is not null");
			return (Criteria) this;
		}

		public Criteria andBatteryEqualTo(Integer value) {
			addCriterion("battery =", value, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryNotEqualTo(Integer value) {
			addCriterion("battery <>", value, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryGreaterThan(Integer value) {
			addCriterion("battery >", value, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryGreaterThanOrEqualTo(Integer value) {
			addCriterion("battery >=", value, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryLessThan(Integer value) {
			addCriterion("battery <", value, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryLessThanOrEqualTo(Integer value) {
			addCriterion("battery <=", value, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryIn(List<Integer> values) {
			addCriterion("battery in", values, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryNotIn(List<Integer> values) {
			addCriterion("battery not in", values, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryBetween(Integer value1, Integer value2) {
			addCriterion("battery between", value1, value2, "battery");
			return (Criteria) this;
		}

		public Criteria andBatteryNotBetween(Integer value1, Integer value2) {
			addCriterion("battery not between", value1, value2, "battery");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table device_alarm_record
	 * @mbg.generated  Thu Dec 12 08:51:35 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_alarm_record
     *
     * @mbggenerated do_not_delete_during_merge Fri May 31 14:30:29 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}