package com.aw.braceletserver.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DevicePosition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.id
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.device_id
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.latitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private BigDecimal latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.longitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private BigDecimal longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.o_latitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private BigDecimal oLatitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.o_longitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private BigDecimal oLongitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.device_utc_time
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Date deviceUtcTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.position_type
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Integer positionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.altitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Float altitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.online_status
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Integer onlineStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.atmosphere
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private BigDecimal atmosphere;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column device_position.battery
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	private Integer battery;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.id
	 * @return  the value of device_position.id
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.id
	 * @param id  the value for device_position.id
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.device_id
	 * @return  the value of device_position.device_id
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.device_id
	 * @param deviceId  the value for device_position.device_id
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.latitude
	 * @return  the value of device_position.latitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.latitude
	 * @param latitude  the value for device_position.latitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.longitude
	 * @return  the value of device_position.longitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.longitude
	 * @param longitude  the value for device_position.longitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.o_latitude
	 * @return  the value of device_position.o_latitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public BigDecimal getoLatitude() {
		return oLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.o_latitude
	 * @param oLatitude  the value for device_position.o_latitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setoLatitude(BigDecimal oLatitude) {
		this.oLatitude = oLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.o_longitude
	 * @return  the value of device_position.o_longitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public BigDecimal getoLongitude() {
		return oLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.o_longitude
	 * @param oLongitude  the value for device_position.o_longitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setoLongitude(BigDecimal oLongitude) {
		this.oLongitude = oLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.device_utc_time
	 * @return  the value of device_position.device_utc_time
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Date getDeviceUtcTime() {
		return deviceUtcTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.device_utc_time
	 * @param deviceUtcTime  the value for device_position.device_utc_time
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setDeviceUtcTime(Date deviceUtcTime) {
		this.deviceUtcTime = deviceUtcTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.position_type
	 * @return  the value of device_position.position_type
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Integer getPositionType() {
		return positionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.position_type
	 * @param positionType  the value for device_position.position_type
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setPositionType(Integer positionType) {
		this.positionType = positionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.altitude
	 * @return  the value of device_position.altitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Float getAltitude() {
		return altitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.altitude
	 * @param altitude  the value for device_position.altitude
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setAltitude(Float altitude) {
		this.altitude = altitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.online_status
	 * @return  the value of device_position.online_status
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Integer getOnlineStatus() {
		return onlineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.online_status
	 * @param onlineStatus  the value for device_position.online_status
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setOnlineStatus(Integer onlineStatus) {
		this.onlineStatus = onlineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.atmosphere
	 * @return  the value of device_position.atmosphere
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public BigDecimal getAtmosphere() {
		return atmosphere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.atmosphere
	 * @param atmosphere  the value for device_position.atmosphere
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setAtmosphere(BigDecimal atmosphere) {
		this.atmosphere = atmosphere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column device_position.battery
	 * @return  the value of device_position.battery
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public Integer getBattery() {
		return battery;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column device_position.battery
	 * @param battery  the value for device_position.battery
	 * @mbg.generated  Sat Nov 16 11:39:14 CST 2019
	 */
	public void setBattery(Integer battery) {
		this.battery = battery;
	}
}