package com.aw.braceletserver.entity;

import java.util.ArrayList;
import java.util.List;

public class DeviceEventRemindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public DeviceEventRemindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Integer value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Integer value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Integer value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Integer value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Integer value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Integer> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Integer> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Integer value1, Integer value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceModelIsNull() {
            addCriterion("device_model is null");
            return (Criteria) this;
        }

        public Criteria andDeviceModelIsNotNull() {
            addCriterion("device_model is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceModelEqualTo(Integer value) {
            addCriterion("device_model =", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotEqualTo(Integer value) {
            addCriterion("device_model <>", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelGreaterThan(Integer value) {
            addCriterion("device_model >", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelGreaterThanOrEqualTo(Integer value) {
            addCriterion("device_model >=", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelLessThan(Integer value) {
            addCriterion("device_model <", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelLessThanOrEqualTo(Integer value) {
            addCriterion("device_model <=", value, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelIn(List<Integer> values) {
            addCriterion("device_model in", values, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotIn(List<Integer> values) {
            addCriterion("device_model not in", values, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelBetween(Integer value1, Integer value2) {
            addCriterion("device_model between", value1, value2, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andDeviceModelNotBetween(Integer value1, Integer value2) {
            addCriterion("device_model not between", value1, value2, "deviceModel");
            return (Criteria) this;
        }

        public Criteria andENameIsNull() {
            addCriterion("e_name is null");
            return (Criteria) this;
        }

        public Criteria andENameIsNotNull() {
            addCriterion("e_name is not null");
            return (Criteria) this;
        }

        public Criteria andENameEqualTo(String value) {
            addCriterion("e_name =", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotEqualTo(String value) {
            addCriterion("e_name <>", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameGreaterThan(String value) {
            addCriterion("e_name >", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameGreaterThanOrEqualTo(String value) {
            addCriterion("e_name >=", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLessThan(String value) {
            addCriterion("e_name <", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLessThanOrEqualTo(String value) {
            addCriterion("e_name <=", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLike(String value) {
            addCriterion("e_name like", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotLike(String value) {
            addCriterion("e_name not like", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameIn(List<String> values) {
            addCriterion("e_name in", values, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotIn(List<String> values) {
            addCriterion("e_name not in", values, "eName");
            return (Criteria) this;
        }

        public Criteria andENameBetween(String value1, String value2) {
            addCriterion("e_name between", value1, value2, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotBetween(String value1, String value2) {
            addCriterion("e_name not between", value1, value2, "eName");
            return (Criteria) this;
        }

        public Criteria andEIndexIsNull() {
            addCriterion("e_index is null");
            return (Criteria) this;
        }

        public Criteria andEIndexIsNotNull() {
            addCriterion("e_index is not null");
            return (Criteria) this;
        }

        public Criteria andEIndexEqualTo(Integer value) {
            addCriterion("e_index =", value, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexNotEqualTo(Integer value) {
            addCriterion("e_index <>", value, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexGreaterThan(Integer value) {
            addCriterion("e_index >", value, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_index >=", value, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexLessThan(Integer value) {
            addCriterion("e_index <", value, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexLessThanOrEqualTo(Integer value) {
            addCriterion("e_index <=", value, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexIn(List<Integer> values) {
            addCriterion("e_index in", values, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexNotIn(List<Integer> values) {
            addCriterion("e_index not in", values, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexBetween(Integer value1, Integer value2) {
            addCriterion("e_index between", value1, value2, "eIndex");
            return (Criteria) this;
        }

        public Criteria andEIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("e_index not between", value1, value2, "eIndex");
            return (Criteria) this;
        }

        public Criteria andETypeIsNull() {
            addCriterion("e_type is null");
            return (Criteria) this;
        }

        public Criteria andETypeIsNotNull() {
            addCriterion("e_type is not null");
            return (Criteria) this;
        }

        public Criteria andETypeEqualTo(Integer value) {
            addCriterion("e_type =", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotEqualTo(Integer value) {
            addCriterion("e_type <>", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeGreaterThan(Integer value) {
            addCriterion("e_type >", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_type >=", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeLessThan(Integer value) {
            addCriterion("e_type <", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeLessThanOrEqualTo(Integer value) {
            addCriterion("e_type <=", value, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeIn(List<Integer> values) {
            addCriterion("e_type in", values, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotIn(List<Integer> values) {
            addCriterion("e_type not in", values, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeBetween(Integer value1, Integer value2) {
            addCriterion("e_type between", value1, value2, "eType");
            return (Criteria) this;
        }

        public Criteria andETypeNotBetween(Integer value1, Integer value2) {
            addCriterion("e_type not between", value1, value2, "eType");
            return (Criteria) this;
        }

        public Criteria andEWeekIsNull() {
            addCriterion("e_week is null");
            return (Criteria) this;
        }

        public Criteria andEWeekIsNotNull() {
            addCriterion("e_week is not null");
            return (Criteria) this;
        }

        public Criteria andEWeekEqualTo(String value) {
            addCriterion("e_week =", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekNotEqualTo(String value) {
            addCriterion("e_week <>", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekGreaterThan(String value) {
            addCriterion("e_week >", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekGreaterThanOrEqualTo(String value) {
            addCriterion("e_week >=", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekLessThan(String value) {
            addCriterion("e_week <", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekLessThanOrEqualTo(String value) {
            addCriterion("e_week <=", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekLike(String value) {
            addCriterion("e_week like", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekNotLike(String value) {
            addCriterion("e_week not like", value, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekIn(List<String> values) {
            addCriterion("e_week in", values, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekNotIn(List<String> values) {
            addCriterion("e_week not in", values, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekBetween(String value1, String value2) {
            addCriterion("e_week between", value1, value2, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEWeekNotBetween(String value1, String value2) {
            addCriterion("e_week not between", value1, value2, "eWeek");
            return (Criteria) this;
        }

        public Criteria andEContentIsNull() {
            addCriterion("e_content is null");
            return (Criteria) this;
        }

        public Criteria andEContentIsNotNull() {
            addCriterion("e_content is not null");
            return (Criteria) this;
        }

        public Criteria andEContentEqualTo(String value) {
            addCriterion("e_content =", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotEqualTo(String value) {
            addCriterion("e_content <>", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentGreaterThan(String value) {
            addCriterion("e_content >", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentGreaterThanOrEqualTo(String value) {
            addCriterion("e_content >=", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentLessThan(String value) {
            addCriterion("e_content <", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentLessThanOrEqualTo(String value) {
            addCriterion("e_content <=", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentLike(String value) {
            addCriterion("e_content like", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotLike(String value) {
            addCriterion("e_content not like", value, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentIn(List<String> values) {
            addCriterion("e_content in", values, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotIn(List<String> values) {
            addCriterion("e_content not in", values, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentBetween(String value1, String value2) {
            addCriterion("e_content between", value1, value2, "eContent");
            return (Criteria) this;
        }

        public Criteria andEContentNotBetween(String value1, String value2) {
            addCriterion("e_content not between", value1, value2, "eContent");
            return (Criteria) this;
        }

        public Criteria andETimeIsNull() {
            addCriterion("e_time is null");
            return (Criteria) this;
        }

        public Criteria andETimeIsNotNull() {
            addCriterion("e_time is not null");
            return (Criteria) this;
        }

        public Criteria andETimeEqualTo(String value) {
            addCriterion("e_time =", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeNotEqualTo(String value) {
            addCriterion("e_time <>", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeGreaterThan(String value) {
            addCriterion("e_time >", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeGreaterThanOrEqualTo(String value) {
            addCriterion("e_time >=", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeLessThan(String value) {
            addCriterion("e_time <", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeLessThanOrEqualTo(String value) {
            addCriterion("e_time <=", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeLike(String value) {
            addCriterion("e_time like", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeNotLike(String value) {
            addCriterion("e_time not like", value, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeIn(List<String> values) {
            addCriterion("e_time in", values, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeNotIn(List<String> values) {
            addCriterion("e_time not in", values, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeBetween(String value1, String value2) {
            addCriterion("e_time between", value1, value2, "eTime");
            return (Criteria) this;
        }

        public Criteria andETimeNotBetween(String value1, String value2) {
            addCriterion("e_time not between", value1, value2, "eTime");
            return (Criteria) this;
        }

        public Criteria andIntervalIsNull() {
            addCriterion("interval is null");
            return (Criteria) this;
        }

        public Criteria andIntervalIsNotNull() {
            addCriterion("interval is not null");
            return (Criteria) this;
        }

        public Criteria andIntervalEqualTo(Integer value) {
            addCriterion("interval =", value, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalNotEqualTo(Integer value) {
            addCriterion("interval <>", value, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalGreaterThan(Integer value) {
            addCriterion("interval >", value, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("interval >=", value, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalLessThan(Integer value) {
            addCriterion("interval <", value, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("interval <=", value, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalIn(List<Integer> values) {
            addCriterion("interval in", values, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalNotIn(List<Integer> values) {
            addCriterion("interval not in", values, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalBetween(Integer value1, Integer value2) {
            addCriterion("interval between", value1, value2, "interval");
            return (Criteria) this;
        }

        public Criteria andIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("interval not between", value1, value2, "interval");
            return (Criteria) this;
        }

        public Criteria andIsVoiceIsNull() {
            addCriterion("is_voice is null");
            return (Criteria) this;
        }

        public Criteria andIsVoiceIsNotNull() {
            addCriterion("is_voice is not null");
            return (Criteria) this;
        }

        public Criteria andIsVoiceEqualTo(Boolean value) {
            addCriterion("is_voice =", value, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceNotEqualTo(Boolean value) {
            addCriterion("is_voice <>", value, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceGreaterThan(Boolean value) {
            addCriterion("is_voice >", value, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_voice >=", value, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceLessThan(Boolean value) {
            addCriterion("is_voice <", value, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceLessThanOrEqualTo(Boolean value) {
            addCriterion("is_voice <=", value, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceIn(List<Boolean> values) {
            addCriterion("is_voice in", values, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceNotIn(List<Boolean> values) {
            addCriterion("is_voice not in", values, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceBetween(Boolean value1, Boolean value2) {
            addCriterion("is_voice between", value1, value2, "isVoice");
            return (Criteria) this;
        }

        public Criteria andIsVoiceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_voice not between", value1, value2, "isVoice");
            return (Criteria) this;
        }

        public Criteria andVoiceLongIsNull() {
            addCriterion("voice_long is null");
            return (Criteria) this;
        }

        public Criteria andVoiceLongIsNotNull() {
            addCriterion("voice_long is not null");
            return (Criteria) this;
        }

        public Criteria andVoiceLongEqualTo(Integer value) {
            addCriterion("voice_long =", value, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongNotEqualTo(Integer value) {
            addCriterion("voice_long <>", value, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongGreaterThan(Integer value) {
            addCriterion("voice_long >", value, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongGreaterThanOrEqualTo(Integer value) {
            addCriterion("voice_long >=", value, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongLessThan(Integer value) {
            addCriterion("voice_long <", value, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongLessThanOrEqualTo(Integer value) {
            addCriterion("voice_long <=", value, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongIn(List<Integer> values) {
            addCriterion("voice_long in", values, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongNotIn(List<Integer> values) {
            addCriterion("voice_long not in", values, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongBetween(Integer value1, Integer value2) {
            addCriterion("voice_long between", value1, value2, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceLongNotBetween(Integer value1, Integer value2) {
            addCriterion("voice_long not between", value1, value2, "voiceLong");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlIsNull() {
            addCriterion("voice_url is null");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlIsNotNull() {
            addCriterion("voice_url is not null");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlEqualTo(String value) {
            addCriterion("voice_url =", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlNotEqualTo(String value) {
            addCriterion("voice_url <>", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlGreaterThan(String value) {
            addCriterion("voice_url >", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("voice_url >=", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlLessThan(String value) {
            addCriterion("voice_url <", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlLessThanOrEqualTo(String value) {
            addCriterion("voice_url <=", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlLike(String value) {
            addCriterion("voice_url like", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlNotLike(String value) {
            addCriterion("voice_url not like", value, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlIn(List<String> values) {
            addCriterion("voice_url in", values, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlNotIn(List<String> values) {
            addCriterion("voice_url not in", values, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlBetween(String value1, String value2) {
            addCriterion("voice_url between", value1, value2, "voiceUrl");
            return (Criteria) this;
        }

        public Criteria andVoiceUrlNotBetween(String value1, String value2) {
            addCriterion("voice_url not between", value1, value2, "voiceUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_event_remind
     *
     * @mbggenerated do_not_delete_during_merge Sat May 18 23:32:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_event_remind
     *
     * @mbggenerated Sat May 18 23:32:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}