package com.aw.braceletserver.entity;

import java.util.Date;

public class Dic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.DIC_CODE
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private String dicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.DIC_NAME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private String dicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.DIC_VALUE
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private String dicValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.VALID
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private String valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.CREATE_USER
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.CREATE_TIME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.UPDATE_USER
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.DIC_CODE
     *
     * @return the value of dic.DIC_CODE
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.DIC_CODE
     *
     * @param dicCode the value for dic.DIC_CODE
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.DIC_NAME
     *
     * @return the value of dic.DIC_NAME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.DIC_NAME
     *
     * @param dicName the value for dic.DIC_NAME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setDicName(String dicName) {
        this.dicName = dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.DIC_VALUE
     *
     * @return the value of dic.DIC_VALUE
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.DIC_VALUE
     *
     * @param dicValue the value for dic.DIC_VALUE
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.VALID
     *
     * @return the value of dic.VALID
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.VALID
     *
     * @param valid the value for dic.VALID
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.CREATE_USER
     *
     * @return the value of dic.CREATE_USER
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.CREATE_USER
     *
     * @param createUser the value for dic.CREATE_USER
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.CREATE_TIME
     *
     * @return the value of dic.CREATE_TIME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.CREATE_TIME
     *
     * @param createTime the value for dic.CREATE_TIME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.UPDATE_USER
     *
     * @return the value of dic.UPDATE_USER
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.UPDATE_USER
     *
     * @param updateUser the value for dic.UPDATE_USER
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.UPDATE_TIME
     *
     * @return the value of dic.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.UPDATE_TIME
     *
     * @param updateTime the value for dic.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 21 16:00:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}