package com.aw.braceletserver.entity;

import java.util.Date;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.GROUP_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.GROUP_NAME
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.ICON
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.CREATE_TIME
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.P_GROUP_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    private Integer pGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.USER_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.GROUP_ID
     *
     * @return the value of group.GROUP_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.GROUP_ID
     *
     * @param groupId the value for group.GROUP_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.GROUP_NAME
     *
     * @return the value of group.GROUP_NAME
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.GROUP_NAME
     *
     * @param groupName the value for group.GROUP_NAME
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.ICON
     *
     * @return the value of group.ICON
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.ICON
     *
     * @param icon the value for group.ICON
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.CREATE_TIME
     *
     * @return the value of group.CREATE_TIME
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.CREATE_TIME
     *
     * @param createTime the value for group.CREATE_TIME
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.P_GROUP_ID
     *
     * @return the value of group.P_GROUP_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public Integer getpGroupId() {
        return pGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.P_GROUP_ID
     *
     * @param pGroupId the value for group.P_GROUP_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public void setpGroupId(Integer pGroupId) {
        this.pGroupId = pGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.USER_ID
     *
     * @return the value of group.USER_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.USER_ID
     *
     * @param userId the value for group.USER_ID
     *
     * @mbggenerated Sun May 19 22:07:46 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}