package com.aw.braceletserver.entity;

import java.util.Date;

public class Health {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.ID
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.DEVICE_SERIAL_NUM
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private String deviceSerialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.USER_ID
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.BLOOD_SUGAR
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Float bloodSugar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.CREATE_TIME
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.DISASTOLIC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Float disastolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.SHRINK
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Float shrink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.HEART_BEAT
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Float heartBeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.STEPS
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer steps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.BLOOD_PRESSURE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Float bloodPressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.BODY_TEMPERATURE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Float bodyTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.DEEP_SLEEP_SEC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer deepSleepSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.LIGHT_SLEEP_SEC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer lightSleepSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.ROLL
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer roll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.WAKE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer wake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health.QUALITY
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    private Integer quality;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.ID
     *
     * @return the value of health.ID
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.ID
     *
     * @param id the value for health.ID
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.DEVICE_SERIAL_NUM
     *
     * @return the value of health.DEVICE_SERIAL_NUM
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public String getDeviceSerialNum() {
        return deviceSerialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.DEVICE_SERIAL_NUM
     *
     * @param deviceSerialNum the value for health.DEVICE_SERIAL_NUM
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setDeviceSerialNum(String deviceSerialNum) {
        this.deviceSerialNum = deviceSerialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.USER_ID
     *
     * @return the value of health.USER_ID
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.USER_ID
     *
     * @param userId the value for health.USER_ID
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.BLOOD_SUGAR
     *
     * @return the value of health.BLOOD_SUGAR
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Float getBloodSugar() {
        return bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.BLOOD_SUGAR
     *
     * @param bloodSugar the value for health.BLOOD_SUGAR
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setBloodSugar(Float bloodSugar) {
        this.bloodSugar = bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.CREATE_TIME
     *
     * @return the value of health.CREATE_TIME
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.CREATE_TIME
     *
     * @param createTime the value for health.CREATE_TIME
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.DISASTOLIC
     *
     * @return the value of health.DISASTOLIC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Float getDisastolic() {
        return disastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.DISASTOLIC
     *
     * @param disastolic the value for health.DISASTOLIC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setDisastolic(Float disastolic) {
        this.disastolic = disastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.SHRINK
     *
     * @return the value of health.SHRINK
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Float getShrink() {
        return shrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.SHRINK
     *
     * @param shrink the value for health.SHRINK
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setShrink(Float shrink) {
        this.shrink = shrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.HEART_BEAT
     *
     * @return the value of health.HEART_BEAT
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Float getHeartBeat() {
        return heartBeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.HEART_BEAT
     *
     * @param heartBeat the value for health.HEART_BEAT
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setHeartBeat(Float heartBeat) {
        this.heartBeat = heartBeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.STEPS
     *
     * @return the value of health.STEPS
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getSteps() {
        return steps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.STEPS
     *
     * @param steps the value for health.STEPS
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.BLOOD_PRESSURE
     *
     * @return the value of health.BLOOD_PRESSURE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Float getBloodPressure() {
        return bloodPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.BLOOD_PRESSURE
     *
     * @param bloodPressure the value for health.BLOOD_PRESSURE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setBloodPressure(Float bloodPressure) {
        this.bloodPressure = bloodPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.BODY_TEMPERATURE
     *
     * @return the value of health.BODY_TEMPERATURE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Float getBodyTemperature() {
        return bodyTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.BODY_TEMPERATURE
     *
     * @param bodyTemperature the value for health.BODY_TEMPERATURE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setBodyTemperature(Float bodyTemperature) {
        this.bodyTemperature = bodyTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.DEEP_SLEEP_SEC
     *
     * @return the value of health.DEEP_SLEEP_SEC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getDeepSleepSec() {
        return deepSleepSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.DEEP_SLEEP_SEC
     *
     * @param deepSleepSec the value for health.DEEP_SLEEP_SEC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setDeepSleepSec(Integer deepSleepSec) {
        this.deepSleepSec = deepSleepSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.LIGHT_SLEEP_SEC
     *
     * @return the value of health.LIGHT_SLEEP_SEC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getLightSleepSec() {
        return lightSleepSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.LIGHT_SLEEP_SEC
     *
     * @param lightSleepSec the value for health.LIGHT_SLEEP_SEC
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setLightSleepSec(Integer lightSleepSec) {
        this.lightSleepSec = lightSleepSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.ROLL
     *
     * @return the value of health.ROLL
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getRoll() {
        return roll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.ROLL
     *
     * @param roll the value for health.ROLL
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setRoll(Integer roll) {
        this.roll = roll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.WAKE
     *
     * @return the value of health.WAKE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getWake() {
        return wake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.WAKE
     *
     * @param wake the value for health.WAKE
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setWake(Integer wake) {
        this.wake = wake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health.QUALITY
     *
     * @return the value of health.QUALITY
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public Integer getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health.QUALITY
     *
     * @param quality the value for health.QUALITY
     *
     * @mbggenerated Wed May 22 17:22:24 CST 2019
     */
    public void setQuality(Integer quality) {
        this.quality = quality;
    }
}