package com.aw.braceletserver.entity;

import java.util.Date;

public class TxUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.USER_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.USER_NAME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.PASSWORD
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.LOGIN_NAME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.TOKEN
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.AVATAR
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.EMAIL
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.CELLPHONE
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String cellphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.ADDRESS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.SEX
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.DEVICE_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Integer deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.GROUP_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.ONLINE_STATUS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String onlineStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.LOGIN_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Date loginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.LOGOUT_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Date logoutTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.LOGIN_IP
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String loginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.CREATE_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.STATUS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.HEIGHT
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Integer height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tx_user.WEIGHT
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	private Integer weight;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.USER_ID
	 * @return  the value of tx_user.USER_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.USER_ID
	 * @param userId  the value for tx_user.USER_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.USER_NAME
	 * @return  the value of tx_user.USER_NAME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.USER_NAME
	 * @param userName  the value for tx_user.USER_NAME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.PASSWORD
	 * @return  the value of tx_user.PASSWORD
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.PASSWORD
	 * @param password  the value for tx_user.PASSWORD
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.LOGIN_NAME
	 * @return  the value of tx_user.LOGIN_NAME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.LOGIN_NAME
	 * @param loginName  the value for tx_user.LOGIN_NAME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.TOKEN
	 * @return  the value of tx_user.TOKEN
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.TOKEN
	 * @param token  the value for tx_user.TOKEN
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.AVATAR
	 * @return  the value of tx_user.AVATAR
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.AVATAR
	 * @param avatar  the value for tx_user.AVATAR
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.EMAIL
	 * @return  the value of tx_user.EMAIL
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.EMAIL
	 * @param email  the value for tx_user.EMAIL
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.CELLPHONE
	 * @return  the value of tx_user.CELLPHONE
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getCellphone() {
		return cellphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.CELLPHONE
	 * @param cellphone  the value for tx_user.CELLPHONE
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.ADDRESS
	 * @return  the value of tx_user.ADDRESS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.ADDRESS
	 * @param address  the value for tx_user.ADDRESS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.SEX
	 * @return  the value of tx_user.SEX
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.SEX
	 * @param sex  the value for tx_user.SEX
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.DEVICE_ID
	 * @return  the value of tx_user.DEVICE_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Integer getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.DEVICE_ID
	 * @param deviceId  the value for tx_user.DEVICE_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.GROUP_ID
	 * @return  the value of tx_user.GROUP_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.GROUP_ID
	 * @param groupId  the value for tx_user.GROUP_ID
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.ONLINE_STATUS
	 * @return  the value of tx_user.ONLINE_STATUS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getOnlineStatus() {
		return onlineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.ONLINE_STATUS
	 * @param onlineStatus  the value for tx_user.ONLINE_STATUS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setOnlineStatus(String onlineStatus) {
		this.onlineStatus = onlineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.LOGIN_TIME
	 * @return  the value of tx_user.LOGIN_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Date getLoginTime() {
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.LOGIN_TIME
	 * @param loginTime  the value for tx_user.LOGIN_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.LOGOUT_TIME
	 * @return  the value of tx_user.LOGOUT_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Date getLogoutTime() {
		return logoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.LOGOUT_TIME
	 * @param logoutTime  the value for tx_user.LOGOUT_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.LOGIN_IP
	 * @return  the value of tx_user.LOGIN_IP
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getLoginIp() {
		return loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.LOGIN_IP
	 * @param loginIp  the value for tx_user.LOGIN_IP
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.CREATE_TIME
	 * @return  the value of tx_user.CREATE_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.CREATE_TIME
	 * @param createTime  the value for tx_user.CREATE_TIME
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.STATUS
	 * @return  the value of tx_user.STATUS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.STATUS
	 * @param status  the value for tx_user.STATUS
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.HEIGHT
	 * @return  the value of tx_user.HEIGHT
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.HEIGHT
	 * @param height  the value for tx_user.HEIGHT
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tx_user.WEIGHT
	 * @return  the value of tx_user.WEIGHT
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tx_user.WEIGHT
	 * @param weight  the value for tx_user.WEIGHT
	 * @mbg.generated  Wed May 22 11:28:27 CST 2019
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}
}