package com.aw.braceletserver.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CODE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NO
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REAL_NAME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PHONE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TELPHONE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SEX
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ONLINE_STATUS
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGIN_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGOUT_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private Date logoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGIN_IP
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CITY
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PROVINCE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATE_USER
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATE_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATE_USER
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ONLINE_SET
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String onlineSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATUS
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CODE
     *
     * @return the value of user.CODE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CODE
     *
     * @param code the value for user.CODE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NO
     *
     * @return the value of user.NO
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NO
     *
     * @param no the value for user.NO
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REAL_NAME
     *
     * @return the value of user.REAL_NAME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REAL_NAME
     *
     * @param realName the value for user.REAL_NAME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PHONE
     *
     * @return the value of user.PHONE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PHONE
     *
     * @param phone the value for user.PHONE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TELPHONE
     *
     * @return the value of user.TELPHONE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TELPHONE
     *
     * @param telphone the value for user.TELPHONE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SEX
     *
     * @return the value of user.SEX
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ONLINE_STATUS
     *
     * @return the value of user.ONLINE_STATUS
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ONLINE_STATUS
     *
     * @param onlineStatus the value for user.ONLINE_STATUS
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setOnlineStatus(String onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGIN_TIME
     *
     * @return the value of user.LOGIN_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGIN_TIME
     *
     * @param loginTime the value for user.LOGIN_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGOUT_TIME
     *
     * @return the value of user.LOGOUT_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGOUT_TIME
     *
     * @param logoutTime the value for user.LOGOUT_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGIN_IP
     *
     * @return the value of user.LOGIN_IP
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGIN_IP
     *
     * @param loginIp the value for user.LOGIN_IP
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CITY
     *
     * @return the value of user.CITY
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CITY
     *
     * @param city the value for user.CITY
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PROVINCE
     *
     * @return the value of user.PROVINCE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PROVINCE
     *
     * @param province the value for user.PROVINCE
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATE_USER
     *
     * @return the value of user.CREATE_USER
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATE_USER
     *
     * @param createUser the value for user.CREATE_USER
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATE_TIME
     *
     * @return the value of user.CREATE_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATE_TIME
     *
     * @param createTime the value for user.CREATE_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATE_USER
     *
     * @return the value of user.UPDATE_USER
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATE_USER
     *
     * @param updateUser the value for user.UPDATE_USER
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATE_TIME
     *
     * @return the value of user.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATE_TIME
     *
     * @param updateTime the value for user.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ONLINE_SET
     *
     * @return the value of user.ONLINE_SET
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getOnlineSet() {
        return onlineSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ONLINE_SET
     *
     * @param onlineSet the value for user.ONLINE_SET
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setOnlineSet(String onlineSet) {
        this.onlineSet = onlineSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATUS
     *
     * @return the value of user.STATUS
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATUS
     *
     * @param status the value for user.STATUS
     *
     * @mbg.generated Thu Mar 07 10:45:54 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}