package com.aw.braceletserver.entity;

import java.util.Date;

public class UserCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.PKID
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private String pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.USER_CODE
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.ARTICLE_ID
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.IS_COLLECT
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private String isCollect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.COLLECT_TYPE
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private String collectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.COLLECT_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private Date collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.FIRST_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private Date firstTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.LATELY_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private Date latelyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.READ_TIMES
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private Integer readTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect.CREATE_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.PKID
     *
     * @return the value of user_collect.PKID
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.PKID
     *
     * @param pkid the value for user_collect.PKID
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setPkid(String pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.USER_CODE
     *
     * @return the value of user_collect.USER_CODE
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.USER_CODE
     *
     * @param userCode the value for user_collect.USER_CODE
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.ARTICLE_ID
     *
     * @return the value of user_collect.ARTICLE_ID
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.ARTICLE_ID
     *
     * @param articleId the value for user_collect.ARTICLE_ID
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.IS_COLLECT
     *
     * @return the value of user_collect.IS_COLLECT
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public String getIsCollect() {
        return isCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.IS_COLLECT
     *
     * @param isCollect the value for user_collect.IS_COLLECT
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setIsCollect(String isCollect) {
        this.isCollect = isCollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.COLLECT_TYPE
     *
     * @return the value of user_collect.COLLECT_TYPE
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public String getCollectType() {
        return collectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.COLLECT_TYPE
     *
     * @param collectType the value for user_collect.COLLECT_TYPE
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setCollectType(String collectType) {
        this.collectType = collectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.COLLECT_TIME
     *
     * @return the value of user_collect.COLLECT_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.COLLECT_TIME
     *
     * @param collectTime the value for user_collect.COLLECT_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.FIRST_TIME
     *
     * @return the value of user_collect.FIRST_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public Date getFirstTime() {
        return firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.FIRST_TIME
     *
     * @param firstTime the value for user_collect.FIRST_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.LATELY_TIME
     *
     * @return the value of user_collect.LATELY_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public Date getLatelyTime() {
        return latelyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.LATELY_TIME
     *
     * @param latelyTime the value for user_collect.LATELY_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setLatelyTime(Date latelyTime) {
        this.latelyTime = latelyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.READ_TIMES
     *
     * @return the value of user_collect.READ_TIMES
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public Integer getReadTimes() {
        return readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.READ_TIMES
     *
     * @param readTimes the value for user_collect.READ_TIMES
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setReadTimes(Integer readTimes) {
        this.readTimes = readTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect.CREATE_TIME
     *
     * @return the value of user_collect.CREATE_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect.CREATE_TIME
     *
     * @param createTime the value for user_collect.CREATE_TIME
     *
     * @mbg.generated Mon Mar 11 09:54:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}